name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure you have read both the README and help text before opening an issue
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Please decribe the bug you are experiencing?
      value: "The issue is that..."
    validations:
      required: true
  - type: textarea
    id: what-expedcted
    attributes:
      label: What did you expect to happen?
      description: Expected behaviour
      value: "Expected behaviour"
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: commit
      description: what commit triggered this issue?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
